# Generated by Django 4.0.1 on 2022-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='is_team_leader',
        ),
    ]
