# Generated by Django 4.0.1 on 2022-03-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='device',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='project',
        ),
        migrations.AddField(
            model_name='thing',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='things', to='users.site'),
            preserve_default=False,
        ),
    ]
