# Generated by Django 4.0.1 on 2022-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default='JDECO', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='disco',
            field=models.CharField(default='JDECO', max_length=50),
            preserve_default=False,
        ),
    ]
