# Generated by Django 4.0.1 on 2022-02-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alert_name_site_disco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.site'),
            preserve_default=False,
        ),
    ]
