# Generated by Django 4.0.1 on 2022-03-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_thing_device_remove_thing_project_thing_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='users.dashboard')),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.RemoveField(
            model_name='chart',
            name='project',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
        migrations.AddField(
            model_name='query',
            name='column',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='function',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='statistic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='users.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
