# Generated by Django 4.0.1 on 2022-01-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teamsite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization_Membership',
            new_name='OrganizationMembership',
        ),
        migrations.RenameModel(
            old_name='Team_Membership',
            new_name='TeamMembership',
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
            options={
                'db_table': 'team_project',
            },
        ),
    ]
