# Generated by Django 4.0.1 on 2022-01-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organizationmembership_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=set(),
        ),
    ]
