# Generated by Django 4.0.1 on 2022-02-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ticket_organization_ticket_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
