# Generated by Django 4.0.1 on 2022-01-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_device_thing_remove_project_teams_delete_teamproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('x_label', models.CharField(blank=True, max_length=50, null=True)),
                ('y_label', models.CharField(blank=True, max_length=50, null=True)),
                ('x_scale', models.DecimalField(decimal_places=2, max_digits=2)),
                ('y_scale', models.DecimalField(decimal_places=2, max_digits=2)),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('query', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
            options={
                'db_table': 'chart',
            },
        ),
    ]
