# Generated by Django 4.0.1 on 2022-03-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ticket_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='emails',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='operation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='period',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
