# Generated by Django 4.0.1 on 2022-03-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_statistic_query'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
    ]
