# Generated by Django 4.0.1 on 2022-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alert_description_alert_emails_alert_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dashboard',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
