# Generated by Django 4.0.1 on 2022-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='pallet',
            field=models.TextField(choices=[('Pallet1', 'Pallet1'), ('Pallet2', 'Pallet1'), ('Pallet3', 'Pallet1'), ('Pallet4', 'Pallet1')], default='Pallet1', max_length=7),
        ),
    ]
