# Generated by Django 4.0.1 on 2022-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ticket_description_alter_ticket_title_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='theme',
            field=models.CharField(default='org', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='palestine', max_length=50),
            preserve_default=False,
        ),
    ]
