# Generated by Django 4.0.1 on 2022-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_statistic_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='pallet',
            field=models.TextField(choices=[('pallet1', 'Pallet1'), ('pallet2', 'Pallet1'), ('pallet3', 'Pallet1'), ('pallet4', 'Pallet1')], default='pallet1', max_length=7),
        ),
    ]
