# Generated by Django 4.0.1 on 2022-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_statistic_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='labels',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
