# Generated by Django 4.0.1 on 2022-02-01 08:28

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_name_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('temperature', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
