# Generated by Django 4.0.1 on 2022-02-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_metric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metric',
            table='metric',
        ),
    ]
