# Generated by Django 4.0.1 on 2022-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_metric_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
